---
title: "Introduction"
output: html_document
---


When studying a community, one of the principal components to consider is its food web. First models that studied population dynamics were generally considering the interactions between only two species (e. g., Canale 1970; Rosenzweig & MacArthur 1963). However, in nature, food webs that only include two species and whom behavior only depends on these two are quite uncommon. Most of the time, they are way more complex and involve more than two species (Hastings & Powell, 1991). In that regard, some researchers stated that any food webs study should involve at least three species in order not to lose to much information (Price *et al*., 1980; Rosenzweig, 1973). 

At first, researchers concentrated their food webs works on equilibrium analysis because they assumed that what was observed in nature was the equilibrium state of dynamics models. Thereafter, different studies declared that chaos plays an important role in ecological models. The simplest definition of chaos would be the extreme sensibility to initial conditions in the resulting behavior of a model (Hasting *et al*. 1993). This concept has been discovered in population dynamics during the mid-1970’s. For continuous time model in ecology, it was soon after that. One of the first paper about chaos in ecology was May’s in 1974. Although Hassell et al. (1976) debated on the parameters biological realism of some model and others mentioned that evolution tend to favor systems that don’t have a chaotic behavior, (McCann & Yozis, 1994), many papers reinforce afterwards the importance of chaos in ecology (Schaffer & Kot, 1985). 

Studying chaos in a continuous time model including three species, Hastings & Powell (1991) contributed to the significance and understanding of chaos in ecological systems. Their paper is substantial because it leaded to a lot of other studies on food webs dynamics and chaos (Gakkhar and Singh, 2011). In the current paper, we used the same equations and parameters values as Hastings and Powell to replicate their model. We were able to reproduce all the figures in their papers using *Julia v1.0.3*. 


